service:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: production=front
  tty: true
  image: registry.cn-hangzhou.aliyuncs.com/saas/saas-sub-admin-frontend:0.1.8
  stdin_open: true