version: '3'
services:
  node:
    image: registry.cn-hangzhou.aliyuncs.com/wangbinxiang/saas-dev-node:0.1.0
    volumes:
      - .:/usr/src/app
    networks:
      default:
        aliases:
         - saas-local-sub-frontend
    container_name: saas-sub-frontend
    command: npm run dev-docker-babel-compile
networks:
  default:
    external:
      name: saas-local-network