service:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: dev=front
  tty: true
  command:
  - npm
  - run
  - pm2-docker-sandbox
  image: registry-internal.cn-hangzhou.aliyuncs.com/saas/saas-sub-frontend:VERSION
  stdin_open: true